apiVersion: compute.ionoscloud.io/v1alpha1
kind: NSGFirewallRule
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/nsgfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: SG Rule
    nsgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    protocol: TCP
    sourceIpSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sourceMac: 00:0a:95:9d:68:15
    targetIpSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    type: EGRESS

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/nsgfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: de/txl
    name: Datacenter NSG Example

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: NSG
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/nsgfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Example NSG Description
    name: Example NSG
