apiVersion: compute.ionoscloud.io/v1alpha1
kind: Nic
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/nic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dhcp: true
    firewallActive: true
    firewallType: INGRESS
    lanSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: NIC
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/nic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    name: Datacenter Example
    secAuthProtection: false

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Ipblock
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/nic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: us/las
    name: IP Block Example
    size: 1

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/nic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan
    public: true

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/nic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ZONE_1
    cores: 1
    cpuFamily: INTEL_XEON
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    imageName: Ubuntu-20.04
    imagePasswordSecretRef:
      key: password
      name: pwsecret
      namespace: upbound-system
    name: Server Example
    nic:
      dhcp: true
      firewallActive: true
      lanSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    ram: 1024
    volume:
      diskType: SSD
      name: system
      size: 14
---

apiVersion: v1
kind: Secret
metadata:
  name: pwsecret
  namespace: upbound-system
stringData:
  password: "Upboundtest1"
