apiVersion: container.ionos.m.upbound.io/v1alpha1
kind: RegistryToken
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/registrytoken
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    expiryDate: 2023-01-13 16:27:42Z
    registryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    savePasswordToFile: pass.txt
    scopes:
    - actions:
      - push
      name: Scope1
      type: repository
    status: enabled

---

apiVersion: container.ionos.m.upbound.io/v1alpha1
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/registrytoken
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    garbageCollectionSchedule:
    - days:
      - Monday
      - Tuesday
      time: 05:19:00+00:00
    location: de/fra
