apiVersion: natgateway.ionoscloud.io/v1alpha1
kind: Natgateway
metadata:
  annotations:
    meta.upbound.io/example-id: natgateway/v1alpha1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    lans:
    - gatewayIps:
      - 10.11.2.5
      idSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    name: example
    publicIps:
    - ${ionoscloud_ipblock.example.ips[0]}
    - ${ionoscloud_ipblock.example.ips[1]}

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: natgateway/v1alpha1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    name: Datacenter Example
    secAuthProtection: false

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Ipblock
metadata:
  annotations:
    meta.upbound.io/example-id: natgateway/v1alpha1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: us/las
    name: IP Block Example
    size: 2

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: natgateway/v1alpha1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example
    public: true
