apiVersion: postgresql.ionoscloud.io/v1alpha1
kind: PostgresqlDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/postgresqldatabase
  labels:
    testing.upbound.io/example-name: example_pg_database
  name: example-pg-database
  namespace: upbound-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: exampledatabase
    owner: exampleuser
