apiVersion: postgresql.ionoscloud.io/v1alpha1
kind: PostgresqlUser
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/postgresqluser
  labels:
    testing.upbound.io/example-name: example_pg_user
  name: example-pg-user
  namespace: upbound-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    passwordSecretRef:
      key: password
      name: user-secret
      namespace: upbound-system
    username: exampleuser

---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: upbound-system
stringData:
  password: "Upboundtest!"

