apiVersion: vpnipsec.ionoscloud.io/v1alpha1
kind: VpnIpsecGateway
metadata:
  annotations:
    meta.upbound.io/example-id: vpnipsec/v1alpha1/vpnipsecgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    connections:
    - datacenterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_datacenter
      ipv4Cidr: 192.168.100.10/24
      lanIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_lan
    description: This gateway connects site A to VDC X.
    gatewayIpSelector:
      matchLabels:
        testing.upbound.io/example-name: test_ipblock
    location: de/fra
    name: ipsec_gateway_basic
    version: IKEv2

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: vpnipsec/v1alpha1/vpnipsecgateway
  labels:
    testing.upbound.io/example-name: test_datacenter
  name: test-datacenter
  namespace: upbound-system
spec:
  forProvider:
    location: de/fra
    name: test_vpn_gateway_basic

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Ipblock
metadata:
  annotations:
    meta.upbound.io/example-id: vpnipsec/v1alpha1/vpnipsecgateway
  labels:
    testing.upbound.io/example-name: test_ipblock
  name: test-ipblock
  namespace: upbound-system
spec:
  forProvider:
    location: de/fra
    name: test_ipblock_basic
    size: 1

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: vpnipsec/v1alpha1/vpnipsecgateway
  labels:
    testing.upbound.io/example-name: test_lan
  name: test-lan
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_datacenter
    name: test_lan_basic
    public: false
