apiVersion: s3.ionoscloud.io/v1alpha1
kind: BucketServerSideEncryptionConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucketserversideencryptionconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    rule:
    - {}

---

apiVersion: s3.ionoscloud.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucketserversideencryptionconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider: {}
