apiVersion: s3.ionoscloud.io/v1alpha1
kind: BucketLifecycleConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucketlifecycleconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    rule:
    - expiration:
      - days: 90
      id: Logs delete
      prefix: /logs
      status: Enabled

---

apiVersion: s3.ionoscloud.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucketlifecycleconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider: {}
