apiVersion: upjet-ionoscloud.m.ionoscloud.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
  namespace: upbound-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-provider-secret
      namespace: crossplane-system
      key: credentials
