apiVersion: upjet-ionoscloud.m.ionoscloud.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: cluster-ionos-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: ionos-credentials
      key: credentials
