apiVersion: mongodb.ionoscloud.io/v1alpha1
kind: MongodbCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mongodb/v1alpha1/mongodbcluster
  labels:
    testing.upbound.io/example-name: example_mongo_cluster
  name: example-mongo-cluster
spec:
  forProvider:
    connections:
      - cidrList:
          - 192.168.1.108/24
        datacenterIdSelector:
          matchLabels:
            testing.upbound.io/example-name: datacenter_example
        lanIdSelector:
          matchLabels:
            testing.upbound.io/example-name: lan_example
    displayName: example_mongo_cluster
    instances: 1
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: datacenter_example
    maintenanceWindow:
      - dayOfTheWeek: Sunday
        time: "09:00:00"
    mongodbVersion: "5.0"
    templateId: 6b78ea06-ee0e-4689-998c-fc9c46e781f6
