apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/datacenter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: datacenter description
    location: us/las
    name: Datacenter Example
    secAuthProtection: false
