apiVersion: compute.ionoscloud.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/group
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accessActivityLog: true
    accessAndManageCertificates: true
    accessAndManageMonitoring: true
    createBackupUnit: true
    createDatacenter: true
    createFlowLog: true
    createInternetAccess: true
    createK8SCluster: true
    createPcc: true
    createSnapshot: true
    manageDbaas: true
    name: Group Example
    reserveIp: true
    s3Privilege: true
    userIdsRefs:
    - name: example1
    - name: example2

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/group
  labels:
    testing.upbound.io/example-name: example1
  name: example1
spec:
  forProvider:
    administrator: false
    email: unique_email.com
    firstName: user1
    forceSecAuth: false
    lastName: user1
    passwordSecretRef:
      key: attribute.result
      name: example-password
      namespace: upbound-system

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/group
  labels:
    testing.upbound.io/example-name: example2
  name: example2
spec:
  forProvider:
    administrator: false
    email: unique_email.com
    firstName: user2
    forceSecAuth: false
    lastName: user2
    passwordSecretRef:
      key: attribute.result
      name: example-password
      namespace: upbound-system
