apiVersion: compute.ionoscloud.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ZONE_1
    bus: VIRTIO
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    diskType: SSD Standard
    imageName: ubuntu:latest
    imagePassword: "replaceMe"
    name: Volume Example
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    size: 5
    userData: foo

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Datacenter Description
    location: de/fra
    name: Datacenter Example
    secAuthProtection: false

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example
    public: true

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ZONE_1
    cores: 1
    cpuFamily: INTEL_XEON
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    imageName:  ubuntu:latest
    imagePasswordSecretRef:
      key: password
      name: example-password
      namespace: upbound-system
    name: Server Example
    nic:
    - dhcp: true
      firewall:
      - name: SSH
        portRangeEnd: 22
        portRangeStart: 22
        protocol: TCP
        sourceMac: 00:0a:95:9d:68:17
        type: EGRESS
      firewallActive: true
      firewallType: BIDIRECTIONAL
      lanSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      name: system
    ram: 1024
    type: ENTERPRISE
    volume:
    - availabilityZone: ZONE_1
      bus: VIRTIO
      diskType: SSD Standard
      name: system
      size: 5
      userData: foo
