apiVersion: mariadbv2.m.ionoscloud.io/v1alpha1
kind: MariadbCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mariadbv2/v1alpha1/mariadbcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    backup:
      location: eu-central-3
      retentionDays: 7
    connections:
      datacenterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      lanIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      primaryInstanceAddress: 192.168.2.101/24
    credentials:
      database: my_database
      passwordSecretRef:
        key: attribute.result
        name: example-password
      username: dbadmin
    description: MariaDB cluster
    instances:
      cores: 1
      count: 1
      ram: 4
      storageSize: 10
    location: de/txl
    logsEnabled: true
    maintenanceWindow:
      dayOfTheWeek: Sunday
      time: "09:00:00"
    metricsEnabled: true
    name: my-mariadb-cluster
    version: "11.4"

---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: mariadbv2/v1alpha1/mariadbcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: de/txl
    name: example

---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: mariadbv2/v1alpha1/mariadbcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example
    public: false
