// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Group.
func (mg *Group) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.UserIds),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.UserIdsRefs,
		Selector:      mg.Spec.ForProvider.UserIdsSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.UserIds")
	}
	mg.Spec.ForProvider.UserIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.UserIdsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.UserIds),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.UserIdsRefs,
		Selector:      mg.Spec.InitProvider.UserIdsSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.UserIds")
	}
	mg.Spec.InitProvider.UserIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.UserIdsRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this Lan.
func (mg *Lan) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DatacenterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.DatacenterIDRef,
		Selector:     mg.Spec.ForProvider.DatacenterIDSelector,
		To: reference.To{
			List:    &DatacenterList{},
			Managed: &Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DatacenterID")
	}
	mg.Spec.ForProvider.DatacenterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Pcc),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.PccRef,
		Selector:     mg.Spec.ForProvider.PccSelector,
		To: reference.To{
			List:    &CrossconnectList{},
			Managed: &Crossconnect{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Pcc")
	}
	mg.Spec.ForProvider.Pcc = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PccRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DatacenterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.DatacenterIDRef,
		Selector:     mg.Spec.InitProvider.DatacenterIDSelector,
		To: reference.To{
			List:    &DatacenterList{},
			Managed: &Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DatacenterID")
	}
	mg.Spec.InitProvider.DatacenterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Pcc),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.PccRef,
		Selector:     mg.Spec.InitProvider.PccSelector,
		To: reference.To{
			List:    &CrossconnectList{},
			Managed: &Crossconnect{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Pcc")
	}
	mg.Spec.InitProvider.Pcc = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PccRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Nic.
func (mg *Nic) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DatacenterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.DatacenterIDRef,
		Selector:     mg.Spec.ForProvider.DatacenterIDSelector,
		To: reference.To{
			List:    &DatacenterList{},
			Managed: &Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DatacenterID")
	}
	mg.Spec.ForProvider.DatacenterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.Lan),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.LanRef,
		Selector:     mg.Spec.ForProvider.LanSelector,
		To: reference.To{
			List:    &LanList{},
			Managed: &Lan{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Lan")
	}
	mg.Spec.ForProvider.Lan = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LanRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServerID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ServerIDRef,
		Selector:     mg.Spec.ForProvider.ServerIDSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServerID")
	}
	mg.Spec.ForProvider.ServerID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServerIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DatacenterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.DatacenterIDRef,
		Selector:     mg.Spec.InitProvider.DatacenterIDSelector,
		To: reference.To{
			List:    &DatacenterList{},
			Managed: &Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DatacenterID")
	}
	mg.Spec.InitProvider.DatacenterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.Lan),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.LanRef,
		Selector:     mg.Spec.InitProvider.LanSelector,
		To: reference.To{
			List:    &LanList{},
			Managed: &Lan{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Lan")
	}
	mg.Spec.InitProvider.Lan = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.LanRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServerID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ServerIDRef,
		Selector:     mg.Spec.InitProvider.ServerIDSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServerID")
	}
	mg.Spec.InitProvider.ServerID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServerIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Server.
func (mg *Server) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DatacenterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.DatacenterIDRef,
		Selector:     mg.Spec.ForProvider.DatacenterIDSelector,
		To: reference.To{
			List:    &DatacenterList{},
			Managed: &Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DatacenterID")
	}
	mg.Spec.ForProvider.DatacenterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DatacenterIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Nic); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.Nic[i3].Lan),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.Nic[i3].LanRef,
			Selector:     mg.Spec.ForProvider.Nic[i3].LanSelector,
			To: reference.To{
				List:    &LanList{},
				Managed: &Lan{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Nic[i3].Lan")
		}
		mg.Spec.ForProvider.Nic[i3].Lan = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Nic[i3].LanRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DatacenterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.DatacenterIDRef,
		Selector:     mg.Spec.InitProvider.DatacenterIDSelector,
		To: reference.To{
			List:    &DatacenterList{},
			Managed: &Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DatacenterID")
	}
	mg.Spec.InitProvider.DatacenterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DatacenterIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Nic); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.Nic[i3].Lan),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.InitProvider.Nic[i3].LanRef,
			Selector:     mg.Spec.InitProvider.Nic[i3].LanSelector,
			To: reference.To{
				List:    &LanList{},
				Managed: &Lan{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Nic[i3].Lan")
		}
		mg.Spec.InitProvider.Nic[i3].Lan = reference.ToFloatPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Nic[i3].LanRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Volume.
func (mg *Volume) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DatacenterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.DatacenterIDRef,
		Selector:     mg.Spec.ForProvider.DatacenterIDSelector,
		To: reference.To{
			List:    &DatacenterList{},
			Managed: &Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DatacenterID")
	}
	mg.Spec.ForProvider.DatacenterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServerID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ServerIDRef,
		Selector:     mg.Spec.ForProvider.ServerIDSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServerID")
	}
	mg.Spec.ForProvider.ServerID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServerIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DatacenterID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.DatacenterIDRef,
		Selector:     mg.Spec.InitProvider.DatacenterIDSelector,
		To: reference.To{
			List:    &DatacenterList{},
			Managed: &Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DatacenterID")
	}
	mg.Spec.InitProvider.DatacenterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServerID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ServerIDRef,
		Selector:     mg.Spec.InitProvider.ServerIDSelector,
		To: reference.To{
			List:    &ServerList{},
			Managed: &Server{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServerID")
	}
	mg.Spec.InitProvider.ServerID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServerIDRef = rsp.ResolvedReference

	return nil
}
