// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type MongodbUserInitParameters struct {

	// [string] The unique ID of the cluster. Updates to the value of the field force the cluster to be re-created.
	// +crossplane:generate:reference:type=github.com/ionos-cloud/provider-upjet-ionoscloud/apis/namespaced/mongodb/v1alpha1.MongodbCluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a MongodbCluster in mongodb to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a MongodbCluster in mongodb to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// [string] User password. Updates to the value of the field force the cluster to be re-created.
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// [string] a list of mongodb user roles. Updates to the value of the field force the cluster to be re-created.
	Roles []RolesInitParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// [string] Used for authentication. Updates to the value of the field force the cluster to be re-created.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type MongodbUserObservation struct {

	// [string] The unique ID of the cluster. Updates to the value of the field force the cluster to be re-created.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// [string] a list of mongodb user roles. Updates to the value of the field force the cluster to be re-created.
	Roles []RolesObservation `json:"roles,omitempty" tf:"roles,omitempty"`

	// [string] Used for authentication. Updates to the value of the field force the cluster to be re-created.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type MongodbUserParameters struct {

	// [string] The unique ID of the cluster. Updates to the value of the field force the cluster to be re-created.
	// +crossplane:generate:reference:type=github.com/ionos-cloud/provider-upjet-ionoscloud/apis/namespaced/mongodb/v1alpha1.MongodbCluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a MongodbCluster in mongodb to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a MongodbCluster in mongodb to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// [string] User password. Updates to the value of the field force the cluster to be re-created.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// [string] a list of mongodb user roles. Updates to the value of the field force the cluster to be re-created.
	// +kubebuilder:validation:Optional
	Roles []RolesParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// [string] Used for authentication. Updates to the value of the field force the cluster to be re-created.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RolesInitParameters struct {

	// [string] The user database to use for authentication. Updates to the value of the field force the cluster to be re-created.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// [true] Mongodb user role. Examples: read, readWrite, readAnyDatabase, readWriteAnyDatabase, dbAdmin, dbAdminAnyDatabase, clusterMonitor.
	// A list of mongodb user roles. Examples: read, readWrite, readAnyDatabase
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type RolesObservation struct {

	// [string] The user database to use for authentication. Updates to the value of the field force the cluster to be re-created.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// [true] Mongodb user role. Examples: read, readWrite, readAnyDatabase, readWriteAnyDatabase, dbAdmin, dbAdminAnyDatabase, clusterMonitor.
	// A list of mongodb user roles. Examples: read, readWrite, readAnyDatabase
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type RolesParameters struct {

	// [string] The user database to use for authentication. Updates to the value of the field force the cluster to be re-created.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// [true] Mongodb user role. Examples: read, readWrite, readAnyDatabase, readWriteAnyDatabase, dbAdmin, dbAdminAnyDatabase, clusterMonitor.
	// A list of mongodb user roles. Examples: read, readWrite, readAnyDatabase
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

// MongodbUserSpec defines the desired state of MongodbUser
type MongodbUserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MongodbUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MongodbUserInitParameters `json:"initProvider,omitempty"`
}

// MongodbUserStatus defines the observed state of MongodbUser.
type MongodbUserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MongodbUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MongodbUser is the Schema for the MongodbUsers API. Creates and manages DbaaS MongoDB users.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ionos}
type MongodbUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   MongodbUserSpec   `json:"spec"`
	Status MongodbUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MongodbUserList contains a list of MongodbUsers
type MongodbUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MongodbUser `json:"items"`
}

// Repository type metadata.
var (
	MongodbUser_Kind             = "MongodbUser"
	MongodbUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MongodbUser_Kind}.String()
	MongodbUser_KindAPIVersion   = MongodbUser_Kind + "." + CRDGroupVersion.String()
	MongodbUser_GroupVersionKind = CRDGroupVersion.WithKind(MongodbUser_Kind)
)

func init() {
	SchemeBuilder.Register(&MongodbUser{}, &MongodbUserList{})
}
