apiVersion: objectstorage.ionoscloud.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketlifecycleconfiguration
  labels:
    testing.upbound.io/example-name: lifecycle
  name: ${Rand.RFC1123Subdomain}
spec:
  forProvider: {}
---
apiVersion: objectstorage.ionoscloud.io/v1alpha1
kind: BucketLifecycleConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketlifecycleconfiguration
  labels:
    testing.upbound.io/example-name: lifecycle
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: lifecycle
    rule:
    - expiration:
        days: 30
      id: Logs delete
      prefix: /logs
      status: Enabled
