apiVersion: pg.ionos.m.upbound.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: pg/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    connectionPooler:
    - enabled: true
      poolMode: session
    connections:
    - cidr: 192.168.100.1/24
      datacenterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      lanIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    cores: 4
    credentials:
    - passwordSecretRef:
        key: example-key
        name: example-secret
      username: username
    displayName: PostgreSQL_cluster
    instances: 1
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    maintenanceWindow:
    - dayOfTheWeek: Sunday
      time: "09:00:00"
    postgresVersion: "12"
    ram: 2048
    storageSize: 2048
    storageType: HDD
    synchronizationMode: ASYNCHRONOUS

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: pg/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Datacenter for testing psql cluster
    location: de/txl

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: pg/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    public: false
