apiVersion: pg.ionos.m.upbound.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: pg/v1alpha1/database
  labels:
    testing.upbound.io/example-name: example_pg_database
  name: example-pg-database
  namespace: upbound-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    owner: exampleuser
