apiVersion: pg.ionos.m.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: pg/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example_pg_user
  name: example-pg-user
  namespace: upbound-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    passwordSecretRef:
      key: attribute.result
      name: example-password
    username: exampleuser
