apiVersion: natgateway.m.ionoscloud.io/v1alpha1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: natgateway/v1alpha1/rule
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example
    natgatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    protocol: TCP
    publicIp: 192.96.159.108
    sourceSubnet: 10.0.1.0/24
    targetPortRange:
      end: 1000
      start: 500
    targetSubnet: 10.0.1.0/24
    type: SNAT
