apiVersion: k8s.ionoscloud.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    apiSubnetAllowList:
    - 1.2.3.4/32
    k8sVersion: 1.31.2
    maintenanceWindow:
    - dayOfTheWeek: Sunday
      time: 09:00:00Z
    name: k8sClusterExample
    s3Buckets:
    - nameSelector:
        matchLabels:
          testing.upbound.io/example-name: example
