apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    icmpCode: 8
    icmpType: 1
    nicIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    protocol: ICMP
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sourceIp: ${ionoscloud_ipblock.example.ips[0]}
    sourceMac: 00:0a:95:9d:68:16
    targetIp: ${ionoscloud_ipblock.example.ips[1]}
    type: INGRESS

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    secAuthProtection: false

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Ipblock
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: us/las
    size: 2

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Nic
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dhcp: true
    firewallActive: true
    lanSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cores: 1
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    imageName: Ubuntu-20.04
    imagePasswordSecretRef:
      key: attribute.result
      name: example-password
    nic:
    - dhcp: true
      firewallActive: true
      lanSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    ram: 1024
    volume:
    - diskType: SSD
      name: system
      size: 14
