apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Ipfailover
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ip: ${ionoscloud_ipblock.example.ips[0]}
    lanIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    nicuuidSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    secAuthProtection: false

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Ipblock
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: us/las
    size: 1

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    public: true

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cores: 1
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    imageName: Ubuntu-20.04
    imagePasswordSecretRef:
      key: attribute.result
      name: example-password
    nic:
    - dhcp: true
      firewallActive: true
      ips:
      - ${ionoscloud_ipblock.example.ips[0]}
      lanSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    ram: 1024
    volume:
    - diskType: SSD
      name: system
      size: 14
