apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/lan
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    pccSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    public: false

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/lan
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    secAuthProtection: false

---

apiVersion: private.ionos.m.upbound.io/v1alpha1
kind: Crossconnect
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/lan
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Cross Connect Description
