apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Natgateway
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    lans:
    - gatewayIps:
      - 10.11.2.5
      idSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    publicIps:
    - ${ionoscloud_ipblock.example.ips[0]}
    - ${ionoscloud_ipblock.example.ips[1]}

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    secAuthProtection: false

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Ipblock
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: us/las
    size: 2

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: ionoscloud/v1alpha1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    public: true
