apiVersion: postgresqlv2.ionoscloud.io/v1alpha1
kind: PostgresqlCluster
metadata:
  annotations:
    meta.upbound.io/example-id: postgresqlv2/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backupLocation: de
    connectionPooler: DISABLED
    connections:
      datacenterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      lanIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      primaryInstanceAddress: 192.168.1.100/24
    credentials:
      database: mydb
      passwordSecretRef:
        key: attribute.result
        name: example-password
        namespace: upbound-system
      username: username
    description: Production PostgreSQL cluster
    instances:
      cores: 2
      count: 1
      ram: 4
      storageSize: 10
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    logsEnabled: true
    maintenanceWindow:
      dayOfTheWeek: Sunday
      time: "09:00:00"
    metricsEnabled: true
    name: PostgreSQL_cluster
    replicationMode: ASYNCHRONOUS
    restoreFromBackup:
      recoveryTargetDatetime: "2024-12-06T13:54:08Z"
      sourceBackupId: backup_uuid
    timeouts:
      create: 60m
      delete: 60m
      update: 60m
    version: "17"

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: postgresqlv2/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: de/txl
    name: example

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: postgresqlv2/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example
    public: false
