apiVersion: vpn.ionos.m.upbound.io/v1alpha1
kind: WireguardGateway
metadata:
  annotations:
    meta.upbound.io/example-id: vpn/v1alpha1/wireguardgateway
  labels:
    testing.upbound.io/example-name: gateway
  name: gateway
  namespace: upbound-system
spec:
  forProvider:
    connections:
    - datacenterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: datacenter_example
      ipv4Cidr: 192.168.1.108/24
      lanIdSelector:
        matchLabels:
          testing.upbound.io/example-name: lan_example
    description: description
    gatewayIp: ${ionoscloud_ipblock.ipblock_example.ips[0]}
    interfaceIpv4Cidr: 192.168.1.100/24
    location: de/fra
    maintenanceWindow:
    - dayOfTheWeek: Monday
      time: "09:00:00"
    privateKeySecretRef:
      key: example-key
      name: example-secret
    tier: STANDARD

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: vpn/v1alpha1/wireguardgateway
  labels:
    testing.upbound.io/example-name: datacenter_example
  name: datacenter-example
  namespace: upbound-system
spec:
  forProvider:
    location: de/fra

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Ipblock
metadata:
  annotations:
    meta.upbound.io/example-id: vpn/v1alpha1/wireguardgateway
  labels:
    testing.upbound.io/example-name: ipblock_example
  name: ipblock-example
  namespace: upbound-system
spec:
  forProvider:
    location: de/fra
    size: 1

---

apiVersion: ionoscloud.ionos.m.upbound.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: vpn/v1alpha1/wireguardgateway
  labels:
    testing.upbound.io/example-name: lan_example
  name: lan-example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: datacenter_example
