apiVersion: dns.ionos.m.upbound.io/v1alpha1
kind: Record
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/record
  labels:
    testing.upbound.io/example-name: recordexample
  name: recordexample
  namespace: upbound-system
spec:
  forProvider:
    content: 1.2.3.4
    enabled: false
    priority: 1024
    ttl: 2000
    type: CNAME
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: dns.ionos.m.upbound.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/record
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: description
    enabled: false
