apiVersion: dns.ionos.m.upbound.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/zone
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: description
    enabled: false
