apiVersion: compute.ionoscloud.io/v1alpha1
kind: Unit
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/unit
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    email: example@example-domain.com
    name: BackupUnitExample
    passwordSecretRef:
      key: password
      name: example-password
      namespace: upbound-system
---
apiVersion: v1
kind: Secret
metadata:
  name: example-password
  namespace: upbound-system
stringData:
  password: "Upboundtest!"



