apiVersion: compute.ionoscloud.io/v1alpha1
kind: Ipfailover
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ipSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    lanIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    nicuuidSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    name: Datacenter Example
    secAuthProtection: false

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Ipblock
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: us/las
    name: IP Block Example
    size: 1

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example
    public: true

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/ipfailover
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ZONE_1
    cores: 1
    cpuFamily: INTEL_XEON
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    imageName: Ubuntu-20.04
    imagePasswordSecretRef:
      key: password
      name: example-password
      namespace: upbound-system
    name: Server Example
    nic:
      dhcp: true
      firewallActive: true
      ips:
        - "192.96.159.61"
      lanSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    ram: 1024
    volume:
      diskType: SSD
      name: system
      size: 10
---

apiVersion: v1
kind: Secret
metadata:
  name: example-password
  namespace: upbound-system
stringData:
  password: "Upboundtest1"