apiVersion: auto.ionos.m.upbound.io/v1alpha1
kind: CertificateProvider
metadata:
  annotations:
    meta.upbound.io/example-id: auto/v1alpha1/certificateprovider
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    email: user@example.com
    externalAccountBinding:
    - keyId: some-key-id
      keySecretSecretRef:
        key: example-key
        name: example-secret
    location: de/fra
    server: https://acme-v02.api.letsencrypt.org/directory
