apiVersion: objectstorage.ionoscloud.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    forceDestroy: true
    objectLockEnabled: true
    region: eu-central-3
    tags:
      key1: value1
      key2: value2
    timeouts:
    - create: 10m
      delete: 10m
