apiVersion: postgresql.ionoscloud.io/v1alpha1
kind: PostgresqlCluster
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    connections:
    - cidr: ${local.database_ip_cidr}
      datacenterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      lanIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    cores: 4
    credentials:
    - passwordSecretRef:
        key: attribute.result
        name: example-password
        namespace: upbound-system
      username: username
    displayName: PostgreSQL_cluster
    fromBackup:
    - backupId: backup_uuid
      recoveryTargetTime: "2021-12-06T13:54:08Z"
    instances: 1
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    maintenanceWindow:
    - dayOfTheWeek: Sunday
      time: "09:00:00"
    postgresVersion: 12
    ram: 2048
    storageSize: 2048
    storageType: HDD
    synchronizationMode: ASYNCHRONOUS

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Datacenter for testing dbaas cluster
    location: de/txl
    name: example

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example
    public: false

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/postgresqlcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ZONE_1
    cores: 2
    cpuFamily: INTEL_SKYLAKE
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    imageName: Debian-10-cloud-init.qcow2
    imagePasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: example
    nic:
    - dhcp: true
      lanSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      name: example
    ram: 2048
    volume:
    - diskType: SSD Standard
      name: example
      size: 6
