apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    icmpCode: "8"
    icmpType: "1"
    name: Firewall Example
    nicIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    protocol: ICMP
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sourceMac: 00:0a:95:9d:68:16
    type: INGRESS

---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    name: Datacenter Example
    secAuthProtection: false

---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Nic
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dhcp: true
    firewallActive: true
    lanSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Nic Example
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example
    public: true

---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    availabilityZone: ZONE_1
    cores: 1
    cpuFamily: INTEL_XEON
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    imageName: Ubuntu-20.04
    imagePasswordSecretRef:
      key: password
      name: example-password
      namespace: upbound-system
    name: Server Example
    nic:
      dhcp: true
      firewallActive: true
      lanSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    ram: 1024
    volume:
      diskType: SSD
      name: system
      size: 14
---
apiVersion: v1
kind: Secret
metadata:
  name: example-password
  namespace: upbound-system
stringData:
  password: "Upboundtest1"