apiVersion: compute.ionoscloud.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/server
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cores: 1
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    imageName: "ubuntu:latest"
    imagePasswordSecretRef:
      key: password
      name: pwsecret
      namespace: upbound-system
    name: Crossplane Server Example2
    nic:
      dhcp: true
      firewall:
      - name: SSH2
        portRangeEnd: 23
        portRangeStart: 22
        protocol: TCP
        sourceMac: 00:0a:95:9d:68:18
        type: EGRESS
      firewallActive: true
      firewallType: BIDIRECTIONAL
      lanSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      name: system
    ram: 1024
    type: ENTERPRISE
    volume:
      availabilityZone: ZONE_1
      bus: VIRTIO
      diskType: SSD Standard
      name: system
      size: 10
      userData: foo

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/server
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    name: Datacenter Example
    secAuthProtection: false

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/server
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example
    public: true

---

  apiVersion: v1
  kind: Secret
  metadata:
    name: pwsecret
    namespace: upbound-system
  stringData:
    password: "Upboundtest1"