apiVersion: dns.ionoscloud.io/v1alpha1
kind: DnsZone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/dnszone
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: description
    enabled: true
    name: sdktooling.net

---
apiVersion: certificatemanager.ionoscloud.io/v1alpha1
kind: AutoCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1alpha1/autocertificate
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    commonName: sdktooling.net
    keyAlgorithm: rsa4096
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: My Auto renewed certificatemanager
    providerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subjectAlternativeNames:
    - sdktooling.net

---

apiVersion: certificatemanager.ionoscloud.io/v1alpha1
kind: AutoCertificateProvider
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1alpha1/autocertificate
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    email: sdk-go-v6@cloud.ionos.com
    externalAccountBinding:
    - keyId: some-key-id
      keySecretSecretRef:
        key: password
        name: example-password
        namespace: upbound-system
    location: de/fra
    name: Let's Encrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
---
apiVersion: v1
kind: Secret
metadata:
  name: example-password
  namespace: upbound-system
stringData:
  password: "Upboundtest!"
