apiVersion: certificatemanager.ionoscloud.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1alpha1/certificate
  labels:
    testing.upbound.io/example-name: cert
  name: cert
spec:
  forProvider:
    certificate: "<YOUR_CERTIFICATE>"
    certificateChain: "<YOUR_CERTIFICATE_CHAIN>"
    name: CertificateExample
    privateKeySecretRef:
      key: privateKey
      name: example-secret
      namespace: upbound-system

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
stringData:
  privateKey: "<YOUR_PRIVATE_KEY>"
