apiVersion: nlb.ionoscloud.io/v1alpha1
kind: Networkloadbalancer
metadata:
  annotations:
    meta.upbound.io/example-id: nlb/v1alpha1/networkloadbalancer
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
#    centralLogging: true
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ips:
    - 10.12.118.224
    lbPrivateIps:
    - 10.13.72.225/24
    listenerLanSelector:
      matchLabels:
        testing.upbound.io/example-name: example1
    loggingFormat: '%{+Q}o %{-Q}ci - - [%trg] %r %ST %B "" "" %cp %ms %ft %b %s %TR
      %Tw %Tc %Tr %Ta %tsc %ac %fc %bc %sc %rc %sq %bq %CC %CS %hrl %hsl'
    name: example
    targetLanSelector:
      matchLabels:
        testing.upbound.io/example-name: example2

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: nlb/v1alpha1/networkloadbalancer
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Datacenter Description
    location: us/las
    name: Datacenter Example
    secAuthProtection: false

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: nlb/v1alpha1/networkloadbalancer
  labels:
    testing.upbound.io/example-name: example1
  name: example1
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example 1
    public: false

---

apiVersion: compute.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: nlb/v1alpha1/networkloadbalancer
  labels:
    testing.upbound.io/example-name: example2
  name: example2
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example 2
    public: false
