apiVersion: objectstorage.m.ionoscloud.io/v1alpha1
kind: BucketCorsConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketcorsconfiguration
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    corsRule:
    - allowedHeaders:
      - '*'
      allowedMethods:
      - PUT
      - POST
      allowedOrigins:
      - https://s3-website-test.hashicorp.com
      exposeHeaders:
      - ETag
      id: 1234
      maxAgeSeconds: 3000

---

apiVersion: objectstorage.m.ionoscloud.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketcorsconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider: {}
