apiVersion: cdn.ionoscloud.io/v1alpha1
kind: Distribution
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1alpha1/distribution
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    certificateIdSelector:
      matchLabels:
        testing.upbound.io/example-name: cert
    domain: ${Rand.RFC1123Subdomain}.example.com
    routingRules:
    - prefix: /api
      scheme: https
      upstream:
        caching: true
        geoRestrictions:
          allowList:
          - CN
          - RU
        host: server.example.com
        rateLimitClass: R500
        waf: true
    - prefix: /api2
      scheme: http/https
      upstream:
        caching: false
        geoRestrictions:
          blockList:
          - CN
          - RU
        host: server2.example.com
        rateLimitClass: R10
        waf: false

---
apiVersion: certificatemanager.ionoscloud.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1alpha1/certificate
  labels:
    testing.upbound.io/example-name: cert
  name: cert
spec:
  forProvider:
    certificate: "<REPLACE_WITH_YOUR_CERTIFICATE_PEM>"
    certificateChain: "<REPLACE_WITH_YOUR_CERTIFICATE_PEM>"
    name: CertificateExample
    privateKeySecretRef:
      key: privateKey
      name: example-secret
      namespace: upbound-system

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
stringData:
  privateKey: "<REPLACE_WITH_YOUR_PRIVATE_KEY_PEM>"