apiVersion: alb.m.ionoscloud.io/v1alpha1
kind: Loadbalancer
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    centralLogging: true
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ips:
    - 10.12.118.224
    lbPrivateIps:
    - 10.13.72.225/24
    listenerLanSelector:
      matchLabels:
        testing.upbound.io/example-name: example_1
    loggingFormat: '%{+Q}o %{-Q}ci - - [%trg] %r %ST %B "" "" %cp %ms %ft %b %s %TR
      %Tw %Tc %Tr %Ta %tsc %ac %fc %bc %sc %rc %sq %bq %CC %CS %hrl %hsl'
    name: ALB Example
    targetLanSelector:
      matchLabels:
        testing.upbound.io/example-name: example_2

---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Datacenter
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: datacenter description
    location: us/las
    name: Datacenter Example
    secAuthProtection: false

---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: example_1
  name: example-1
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example
    public: true

---

apiVersion: compute.m.ionoscloud.io/v1alpha1
kind: Lan
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: example_2
  name: example-2
  namespace: upbound-system
spec:
  forProvider:
    datacenterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Lan Example
    public: true
