apiVersion: s3.ionoscloud.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucketcorsconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: darius-v-test
spec:
  forProvider: {}
---
apiVersion: s3.ionoscloud.io/v1alpha1
kind: BucketCorsConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucketcorsconfiguration
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    corsRule:
    - allowedHeaders:
      - '*'
      allowedMethods:
      - PUT
      - POST
      allowedOrigins:
      - https://s3-website-test.hashicorp.com
      exposeHeaders:
      - ETag
      id: 1234
      maxAgeSeconds: 3000


