apiVersion: s3.ionoscloud.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucketobjectlockconfiguration
  labels:
    testing.upbound.io/example-name: object-lock
  name: ${Rand.RFC1123Subdomain}
spec:
  forProvider:
    objectLockEnabled: true
---
apiVersion: s3.ionoscloud.io/v1alpha1
kind: BucketObjectLockConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucketobjectlockconfiguration
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: object-lock
    objectLockEnabled: Enabled
    rule:
      defaultRetention:
        days: 1
        mode: GOVERNANCE